version: '3.9'

networks:
  college4u_c4unetwork:
      external: true

services:
  apiweb:
    build: .
    command: hypercorn main:app --worker-class uvloop --bind 0.0.0.0:7676
    depends_on:
      # - apinginx
      apidb:
        condition: service_healthy
    networks:
      - college4u_c4unetwork
    restart:
      "unless-stopped"
  
  apidb:
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: secretapidbpw292
      PGUSER: postgres
    networks:
      - college4u_c4unetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  apiredis:
    image: redis
    restart: unless-stopped
    networks:
      - college4u_c4unetwork

  # pgadmin:
  #   container_name: pgadmin4
  #   image: biarms/pgadmin4
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: rootutil595
  #   ports:
  #     - "8383:5050"
  #   networks:
  #     - college4u_c4unetwork

  # apinginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/crrapi.cf.conf:ro
  #     - ./crrapi.cf.key:/etc/nginx/ssl/crrapi.cf.key:ro
  #     - ./crrapi.cf.crt:/etc/nginx/ssl/crrapi.cf.crt:ro
  #   ports:
  #     - "8888:443"
  #   networks:
  #     - apinetwork
  #   restart:
  #     "unless-stopped"